# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/mark/Documents/Mark/MTU School/CS3141/TeamJAKK"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/mark/Documents/Mark/MTU School/CS3141/TeamJAKK"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mark/Documents/Mark/MTU School/CS3141/TeamJAKK/CMakeFiles" "/home/mark/Documents/Mark/MTU School/CS3141/TeamJAKK/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mark/Documents/Mark/MTU School/CS3141/TeamJAKK/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GLAD

# Build rule for target.
GLAD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GLAD
.PHONY : GLAD

# fast build rule for target.
GLAD/fast:
	$(MAKE) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/build
.PHONY : GLAD/fast

#=============================================================================
# Target rules for targets named swordthrow

# Build rule for target.
swordthrow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 swordthrow
.PHONY : swordthrow

# fast build rule for target.
swordthrow/fast:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/build
.PHONY : swordthrow/fast

#=============================================================================
# Target rules for targets named STB_IMAGE

# Build rule for target.
STB_IMAGE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 STB_IMAGE
.PHONY : STB_IMAGE

# fast build rule for target.
STB_IMAGE/fast:
	$(MAKE) -f CMakeFiles/STB_IMAGE.dir/build.make CMakeFiles/STB_IMAGE.dir/build
.PHONY : STB_IMAGE/fast

src/Control.o: src/Control.cpp.o

.PHONY : src/Control.o

# target to build an object file
src/Control.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Control.cpp.o
.PHONY : src/Control.cpp.o

src/Control.i: src/Control.cpp.i

.PHONY : src/Control.i

# target to preprocess a source file
src/Control.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Control.cpp.i
.PHONY : src/Control.cpp.i

src/Control.s: src/Control.cpp.s

.PHONY : src/Control.s

# target to generate assembly for a file
src/Control.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Control.cpp.s
.PHONY : src/Control.cpp.s

src/Controller.o: src/Controller.cpp.o

.PHONY : src/Controller.o

# target to build an object file
src/Controller.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Controller.cpp.o
.PHONY : src/Controller.cpp.o

src/Controller.i: src/Controller.cpp.i

.PHONY : src/Controller.i

# target to preprocess a source file
src/Controller.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Controller.cpp.i
.PHONY : src/Controller.cpp.i

src/Controller.s: src/Controller.cpp.s

.PHONY : src/Controller.s

# target to generate assembly for a file
src/Controller.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Controller.cpp.s
.PHONY : src/Controller.cpp.s

src/DungeonMap.o: src/DungeonMap.cpp.o

.PHONY : src/DungeonMap.o

# target to build an object file
src/DungeonMap.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/DungeonMap.cpp.o
.PHONY : src/DungeonMap.cpp.o

src/DungeonMap.i: src/DungeonMap.cpp.i

.PHONY : src/DungeonMap.i

# target to preprocess a source file
src/DungeonMap.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/DungeonMap.cpp.i
.PHONY : src/DungeonMap.cpp.i

src/DungeonMap.s: src/DungeonMap.cpp.s

.PHONY : src/DungeonMap.s

# target to generate assembly for a file
src/DungeonMap.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/DungeonMap.cpp.s
.PHONY : src/DungeonMap.cpp.s

src/DungeonTile.o: src/DungeonTile.cpp.o

.PHONY : src/DungeonTile.o

# target to build an object file
src/DungeonTile.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/DungeonTile.cpp.o
.PHONY : src/DungeonTile.cpp.o

src/DungeonTile.i: src/DungeonTile.cpp.i

.PHONY : src/DungeonTile.i

# target to preprocess a source file
src/DungeonTile.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/DungeonTile.cpp.i
.PHONY : src/DungeonTile.cpp.i

src/DungeonTile.s: src/DungeonTile.cpp.s

.PHONY : src/DungeonTile.s

# target to generate assembly for a file
src/DungeonTile.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/DungeonTile.cpp.s
.PHONY : src/DungeonTile.cpp.s

src/FileLoader.o: src/FileLoader.cpp.o

.PHONY : src/FileLoader.o

# target to build an object file
src/FileLoader.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/FileLoader.cpp.o
.PHONY : src/FileLoader.cpp.o

src/FileLoader.i: src/FileLoader.cpp.i

.PHONY : src/FileLoader.i

# target to preprocess a source file
src/FileLoader.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/FileLoader.cpp.i
.PHONY : src/FileLoader.cpp.i

src/FileLoader.s: src/FileLoader.cpp.s

.PHONY : src/FileLoader.s

# target to generate assembly for a file
src/FileLoader.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/FileLoader.cpp.s
.PHONY : src/FileLoader.cpp.s

src/GameMath.o: src/GameMath.cpp.o

.PHONY : src/GameMath.o

# target to build an object file
src/GameMath.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/GameMath.cpp.o
.PHONY : src/GameMath.cpp.o

src/GameMath.i: src/GameMath.cpp.i

.PHONY : src/GameMath.i

# target to preprocess a source file
src/GameMath.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/GameMath.cpp.i
.PHONY : src/GameMath.cpp.i

src/GameMath.s: src/GameMath.cpp.s

.PHONY : src/GameMath.s

# target to generate assembly for a file
src/GameMath.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/GameMath.cpp.s
.PHONY : src/GameMath.cpp.s

src/GameRunner.o: src/GameRunner.cpp.o

.PHONY : src/GameRunner.o

# target to build an object file
src/GameRunner.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/GameRunner.cpp.o
.PHONY : src/GameRunner.cpp.o

src/GameRunner.i: src/GameRunner.cpp.i

.PHONY : src/GameRunner.i

# target to preprocess a source file
src/GameRunner.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/GameRunner.cpp.i
.PHONY : src/GameRunner.cpp.i

src/GameRunner.s: src/GameRunner.cpp.s

.PHONY : src/GameRunner.s

# target to generate assembly for a file
src/GameRunner.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/GameRunner.cpp.s
.PHONY : src/GameRunner.cpp.s

src/Graphics.o: src/Graphics.cpp.o

.PHONY : src/Graphics.o

# target to build an object file
src/Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Graphics.cpp.o
.PHONY : src/Graphics.cpp.o

src/Graphics.i: src/Graphics.cpp.i

.PHONY : src/Graphics.i

# target to preprocess a source file
src/Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Graphics.cpp.i
.PHONY : src/Graphics.cpp.i

src/Graphics.s: src/Graphics.cpp.s

.PHONY : src/Graphics.s

# target to generate assembly for a file
src/Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Graphics.cpp.s
.PHONY : src/Graphics.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/ResourceManager.o: src/ResourceManager.cpp.o

.PHONY : src/ResourceManager.o

# target to build an object file
src/ResourceManager.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/ResourceManager.cpp.o
.PHONY : src/ResourceManager.cpp.o

src/ResourceManager.i: src/ResourceManager.cpp.i

.PHONY : src/ResourceManager.i

# target to preprocess a source file
src/ResourceManager.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/ResourceManager.cpp.i
.PHONY : src/ResourceManager.cpp.i

src/ResourceManager.s: src/ResourceManager.cpp.s

.PHONY : src/ResourceManager.s

# target to generate assembly for a file
src/ResourceManager.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/ResourceManager.cpp.s
.PHONY : src/ResourceManager.cpp.s

src/Shader.o: src/Shader.cpp.o

.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i

.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s

.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/System.o: src/System.cpp.o

.PHONY : src/System.o

# target to build an object file
src/System.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/System.cpp.o
.PHONY : src/System.cpp.o

src/System.i: src/System.cpp.i

.PHONY : src/System.i

# target to preprocess a source file
src/System.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/System.cpp.i
.PHONY : src/System.cpp.i

src/System.s: src/System.cpp.s

.PHONY : src/System.s

# target to generate assembly for a file
src/System.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/System.cpp.s
.PHONY : src/System.cpp.s

src/Texture.o: src/Texture.cpp.o

.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i

.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s

.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/WindowManager.o: src/WindowManager.cpp.o

.PHONY : src/WindowManager.o

# target to build an object file
src/WindowManager.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/WindowManager.cpp.o
.PHONY : src/WindowManager.cpp.o

src/WindowManager.i: src/WindowManager.cpp.i

.PHONY : src/WindowManager.i

# target to preprocess a source file
src/WindowManager.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/WindowManager.cpp.i
.PHONY : src/WindowManager.cpp.i

src/WindowManager.s: src/WindowManager.cpp.s

.PHONY : src/WindowManager.s

# target to generate assembly for a file
src/WindowManager.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/WindowManager.cpp.s
.PHONY : src/WindowManager.cpp.s

src/enemy.o: src/enemy.cpp.o

.PHONY : src/enemy.o

# target to build an object file
src/enemy.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/enemy.cpp.o
.PHONY : src/enemy.cpp.o

src/enemy.i: src/enemy.cpp.i

.PHONY : src/enemy.i

# target to preprocess a source file
src/enemy.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/enemy.cpp.i
.PHONY : src/enemy.cpp.i

src/enemy.s: src/enemy.cpp.s

.PHONY : src/enemy.s

# target to generate assembly for a file
src/enemy.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/enemy.cpp.s
.PHONY : src/enemy.cpp.s

src/entity.o: src/entity.cpp.o

.PHONY : src/entity.o

# target to build an object file
src/entity.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/entity.cpp.o
.PHONY : src/entity.cpp.o

src/entity.i: src/entity.cpp.i

.PHONY : src/entity.i

# target to preprocess a source file
src/entity.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/entity.cpp.i
.PHONY : src/entity.cpp.i

src/entity.s: src/entity.cpp.s

.PHONY : src/entity.s

# target to generate assembly for a file
src/entity.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/entity.cpp.s
.PHONY : src/entity.cpp.s

src/projectile.o: src/projectile.cpp.o

.PHONY : src/projectile.o

# target to build an object file
src/projectile.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/projectile.cpp.o
.PHONY : src/projectile.cpp.o

src/projectile.i: src/projectile.cpp.i

.PHONY : src/projectile.i

# target to preprocess a source file
src/projectile.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/projectile.cpp.i
.PHONY : src/projectile.cpp.i

src/projectile.s: src/projectile.cpp.s

.PHONY : src/projectile.s

# target to generate assembly for a file
src/projectile.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/projectile.cpp.s
.PHONY : src/projectile.cpp.s

thirdparty/glad.o: thirdparty/glad.c.o

.PHONY : thirdparty/glad.o

# target to build an object file
thirdparty/glad.c.o:
	$(MAKE) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/thirdparty/glad.c.o
.PHONY : thirdparty/glad.c.o

thirdparty/glad.i: thirdparty/glad.c.i

.PHONY : thirdparty/glad.i

# target to preprocess a source file
thirdparty/glad.c.i:
	$(MAKE) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/thirdparty/glad.c.i
.PHONY : thirdparty/glad.c.i

thirdparty/glad.s: thirdparty/glad.c.s

.PHONY : thirdparty/glad.s

# target to generate assembly for a file
thirdparty/glad.c.s:
	$(MAKE) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/thirdparty/glad.c.s
.PHONY : thirdparty/glad.c.s

thirdparty/stb_image.o: thirdparty/stb_image.cpp.o

.PHONY : thirdparty/stb_image.o

# target to build an object file
thirdparty/stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/STB_IMAGE.dir/build.make CMakeFiles/STB_IMAGE.dir/thirdparty/stb_image.cpp.o
.PHONY : thirdparty/stb_image.cpp.o

thirdparty/stb_image.i: thirdparty/stb_image.cpp.i

.PHONY : thirdparty/stb_image.i

# target to preprocess a source file
thirdparty/stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/STB_IMAGE.dir/build.make CMakeFiles/STB_IMAGE.dir/thirdparty/stb_image.cpp.i
.PHONY : thirdparty/stb_image.cpp.i

thirdparty/stb_image.s: thirdparty/stb_image.cpp.s

.PHONY : thirdparty/stb_image.s

# target to generate assembly for a file
thirdparty/stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/STB_IMAGE.dir/build.make CMakeFiles/STB_IMAGE.dir/thirdparty/stb_image.cpp.s
.PHONY : thirdparty/stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... GLAD"
	@echo "... edit_cache"
	@echo "... swordthrow"
	@echo "... rebuild_cache"
	@echo "... STB_IMAGE"
	@echo "... src/Control.o"
	@echo "... src/Control.i"
	@echo "... src/Control.s"
	@echo "... src/Controller.o"
	@echo "... src/Controller.i"
	@echo "... src/Controller.s"
	@echo "... src/DungeonMap.o"
	@echo "... src/DungeonMap.i"
	@echo "... src/DungeonMap.s"
	@echo "... src/DungeonTile.o"
	@echo "... src/DungeonTile.i"
	@echo "... src/DungeonTile.s"
	@echo "... src/FileLoader.o"
	@echo "... src/FileLoader.i"
	@echo "... src/FileLoader.s"
	@echo "... src/GameMath.o"
	@echo "... src/GameMath.i"
	@echo "... src/GameMath.s"
	@echo "... src/GameRunner.o"
	@echo "... src/GameRunner.i"
	@echo "... src/GameRunner.s"
	@echo "... src/Graphics.o"
	@echo "... src/Graphics.i"
	@echo "... src/Graphics.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/ResourceManager.o"
	@echo "... src/ResourceManager.i"
	@echo "... src/ResourceManager.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/System.o"
	@echo "... src/System.i"
	@echo "... src/System.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/WindowManager.o"
	@echo "... src/WindowManager.i"
	@echo "... src/WindowManager.s"
	@echo "... src/enemy.o"
	@echo "... src/enemy.i"
	@echo "... src/enemy.s"
	@echo "... src/entity.o"
	@echo "... src/entity.i"
	@echo "... src/entity.s"
	@echo "... src/projectile.o"
	@echo "... src/projectile.i"
	@echo "... src/projectile.s"
	@echo "... thirdparty/glad.o"
	@echo "... thirdparty/glad.i"
	@echo "... thirdparty/glad.s"
	@echo "... thirdparty/stb_image.o"
	@echo "... thirdparty/stb_image.i"
	@echo "... thirdparty/stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

