# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/mark/Documents/Mark/MTU School/CS3141/TeamJAKK"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/mark/Documents/Mark/MTU School/CS3141/TeamJAKK"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mark/Documents/Mark/MTU School/CS3141/TeamJAKK/CMakeFiles" "/home/mark/Documents/Mark/MTU School/CS3141/TeamJAKK/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mark/Documents/Mark/MTU School/CS3141/TeamJAKK/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named GLAD

# Build rule for target.
GLAD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GLAD
.PHONY : GLAD

# fast build rule for target.
GLAD/fast:
	$(MAKE) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/build
.PHONY : GLAD/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named STB_IMAGE

# Build rule for target.
STB_IMAGE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 STB_IMAGE
.PHONY : STB_IMAGE

# fast build rule for target.
STB_IMAGE/fast:
	$(MAKE) -f CMakeFiles/STB_IMAGE.dir/build.make CMakeFiles/STB_IMAGE.dir/build
.PHONY : STB_IMAGE/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named swordthrow

# Build rule for target.
swordthrow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 swordthrow
.PHONY : swordthrow

# fast build rule for target.
swordthrow/fast:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/build
.PHONY : swordthrow/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named sword_test

# Build rule for target.
sword_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sword_test
.PHONY : sword_test

# fast build rule for target.
sword_test/fast:
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/build
.PHONY : sword_test/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named project_test

# Build rule for target.
project_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project_test
.PHONY : project_test

# fast build rule for target.
project_test/fast:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/build
.PHONY : project_test/fast

src/Collision.o: src/Collision.cpp.o

.PHONY : src/Collision.o

# target to build an object file
src/Collision.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Collision.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Collision.cpp.o
.PHONY : src/Collision.cpp.o

src/Collision.i: src/Collision.cpp.i

.PHONY : src/Collision.i

# target to preprocess a source file
src/Collision.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Collision.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Collision.cpp.i
.PHONY : src/Collision.cpp.i

src/Collision.s: src/Collision.cpp.s

.PHONY : src/Collision.s

# target to generate assembly for a file
src/Collision.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Collision.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Collision.cpp.s
.PHONY : src/Collision.cpp.s

src/Control.o: src/Control.cpp.o

.PHONY : src/Control.o

# target to build an object file
src/Control.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Control.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Control.cpp.o
.PHONY : src/Control.cpp.o

src/Control.i: src/Control.cpp.i

.PHONY : src/Control.i

# target to preprocess a source file
src/Control.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Control.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Control.cpp.i
.PHONY : src/Control.cpp.i

src/Control.s: src/Control.cpp.s

.PHONY : src/Control.s

# target to generate assembly for a file
src/Control.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Control.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Control.cpp.s
.PHONY : src/Control.cpp.s

src/Controller.o: src/Controller.cpp.o

.PHONY : src/Controller.o

# target to build an object file
src/Controller.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Controller.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Controller.cpp.o
.PHONY : src/Controller.cpp.o

src/Controller.i: src/Controller.cpp.i

.PHONY : src/Controller.i

# target to preprocess a source file
src/Controller.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Controller.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Controller.cpp.i
.PHONY : src/Controller.cpp.i

src/Controller.s: src/Controller.cpp.s

.PHONY : src/Controller.s

# target to generate assembly for a file
src/Controller.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Controller.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Controller.cpp.s
.PHONY : src/Controller.cpp.s

src/DungeonMap.o: src/DungeonMap.cpp.o

.PHONY : src/DungeonMap.o

# target to build an object file
src/DungeonMap.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/DungeonMap.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/DungeonMap.cpp.o
.PHONY : src/DungeonMap.cpp.o

src/DungeonMap.i: src/DungeonMap.cpp.i

.PHONY : src/DungeonMap.i

# target to preprocess a source file
src/DungeonMap.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/DungeonMap.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/DungeonMap.cpp.i
.PHONY : src/DungeonMap.cpp.i

src/DungeonMap.s: src/DungeonMap.cpp.s

.PHONY : src/DungeonMap.s

# target to generate assembly for a file
src/DungeonMap.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/DungeonMap.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/DungeonMap.cpp.s
.PHONY : src/DungeonMap.cpp.s

src/DungeonTile.o: src/DungeonTile.cpp.o

.PHONY : src/DungeonTile.o

# target to build an object file
src/DungeonTile.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/DungeonTile.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/DungeonTile.cpp.o
.PHONY : src/DungeonTile.cpp.o

src/DungeonTile.i: src/DungeonTile.cpp.i

.PHONY : src/DungeonTile.i

# target to preprocess a source file
src/DungeonTile.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/DungeonTile.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/DungeonTile.cpp.i
.PHONY : src/DungeonTile.cpp.i

src/DungeonTile.s: src/DungeonTile.cpp.s

.PHONY : src/DungeonTile.s

# target to generate assembly for a file
src/DungeonTile.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/DungeonTile.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/DungeonTile.cpp.s
.PHONY : src/DungeonTile.cpp.s

src/FileLoader.o: src/FileLoader.cpp.o

.PHONY : src/FileLoader.o

# target to build an object file
src/FileLoader.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/FileLoader.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/FileLoader.cpp.o
.PHONY : src/FileLoader.cpp.o

src/FileLoader.i: src/FileLoader.cpp.i

.PHONY : src/FileLoader.i

# target to preprocess a source file
src/FileLoader.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/FileLoader.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/FileLoader.cpp.i
.PHONY : src/FileLoader.cpp.i

src/FileLoader.s: src/FileLoader.cpp.s

.PHONY : src/FileLoader.s

# target to generate assembly for a file
src/FileLoader.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/FileLoader.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/FileLoader.cpp.s
.PHONY : src/FileLoader.cpp.s

src/GameMath.o: src/GameMath.cpp.o

.PHONY : src/GameMath.o

# target to build an object file
src/GameMath.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/GameMath.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/GameMath.cpp.o
.PHONY : src/GameMath.cpp.o

src/GameMath.i: src/GameMath.cpp.i

.PHONY : src/GameMath.i

# target to preprocess a source file
src/GameMath.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/GameMath.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/GameMath.cpp.i
.PHONY : src/GameMath.cpp.i

src/GameMath.s: src/GameMath.cpp.s

.PHONY : src/GameMath.s

# target to generate assembly for a file
src/GameMath.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/GameMath.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/GameMath.cpp.s
.PHONY : src/GameMath.cpp.s

src/GameRunner.o: src/GameRunner.cpp.o

.PHONY : src/GameRunner.o

# target to build an object file
src/GameRunner.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/GameRunner.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/GameRunner.cpp.o
.PHONY : src/GameRunner.cpp.o

src/GameRunner.i: src/GameRunner.cpp.i

.PHONY : src/GameRunner.i

# target to preprocess a source file
src/GameRunner.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/GameRunner.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/GameRunner.cpp.i
.PHONY : src/GameRunner.cpp.i

src/GameRunner.s: src/GameRunner.cpp.s

.PHONY : src/GameRunner.s

# target to generate assembly for a file
src/GameRunner.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/GameRunner.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/GameRunner.cpp.s
.PHONY : src/GameRunner.cpp.s

src/Graphics.o: src/Graphics.cpp.o

.PHONY : src/Graphics.o

# target to build an object file
src/Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Graphics.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Graphics.cpp.o
.PHONY : src/Graphics.cpp.o

src/Graphics.i: src/Graphics.cpp.i

.PHONY : src/Graphics.i

# target to preprocess a source file
src/Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Graphics.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Graphics.cpp.i
.PHONY : src/Graphics.cpp.i

src/Graphics.s: src/Graphics.cpp.s

.PHONY : src/Graphics.s

# target to generate assembly for a file
src/Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Graphics.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Graphics.cpp.s
.PHONY : src/Graphics.cpp.s

src/Hud.o: src/Hud.cpp.o

.PHONY : src/Hud.o

# target to build an object file
src/Hud.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Hud.cpp.o
.PHONY : src/Hud.cpp.o

src/Hud.i: src/Hud.cpp.i

.PHONY : src/Hud.i

# target to preprocess a source file
src/Hud.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Hud.cpp.i
.PHONY : src/Hud.cpp.i

src/Hud.s: src/Hud.cpp.s

.PHONY : src/Hud.s

# target to generate assembly for a file
src/Hud.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Hud.cpp.s
.PHONY : src/Hud.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/MainMenu.o: src/MainMenu.cpp.o

.PHONY : src/MainMenu.o

# target to build an object file
src/MainMenu.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/MainMenu.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/MainMenu.cpp.o
.PHONY : src/MainMenu.cpp.o

src/MainMenu.i: src/MainMenu.cpp.i

.PHONY : src/MainMenu.i

# target to preprocess a source file
src/MainMenu.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/MainMenu.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/MainMenu.cpp.i
.PHONY : src/MainMenu.cpp.i

src/MainMenu.s: src/MainMenu.cpp.s

.PHONY : src/MainMenu.s

# target to generate assembly for a file
src/MainMenu.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/MainMenu.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/MainMenu.cpp.s
.PHONY : src/MainMenu.cpp.s

src/ResourceManager.o: src/ResourceManager.cpp.o

.PHONY : src/ResourceManager.o

# target to build an object file
src/ResourceManager.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/ResourceManager.cpp.o
.PHONY : src/ResourceManager.cpp.o

src/ResourceManager.i: src/ResourceManager.cpp.i

.PHONY : src/ResourceManager.i

# target to preprocess a source file
src/ResourceManager.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/ResourceManager.cpp.i
.PHONY : src/ResourceManager.cpp.i

src/ResourceManager.s: src/ResourceManager.cpp.s

.PHONY : src/ResourceManager.s

# target to generate assembly for a file
src/ResourceManager.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/ResourceManager.cpp.s
.PHONY : src/ResourceManager.cpp.s

src/Shader.o: src/Shader.cpp.o

.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Shader.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i

.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Shader.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s

.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Shader.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/System.o: src/System.cpp.o

.PHONY : src/System.o

# target to build an object file
src/System.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/System.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/System.cpp.o
.PHONY : src/System.cpp.o

src/System.i: src/System.cpp.i

.PHONY : src/System.i

# target to preprocess a source file
src/System.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/System.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/System.cpp.i
.PHONY : src/System.cpp.i

src/System.s: src/System.cpp.s

.PHONY : src/System.s

# target to generate assembly for a file
src/System.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/System.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/System.cpp.s
.PHONY : src/System.cpp.s

src/TextBox.o: src/TextBox.cpp.o

.PHONY : src/TextBox.o

# target to build an object file
src/TextBox.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/TextBox.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/TextBox.cpp.o
.PHONY : src/TextBox.cpp.o

src/TextBox.i: src/TextBox.cpp.i

.PHONY : src/TextBox.i

# target to preprocess a source file
src/TextBox.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/TextBox.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/TextBox.cpp.i
.PHONY : src/TextBox.cpp.i

src/TextBox.s: src/TextBox.cpp.s

.PHONY : src/TextBox.s

# target to generate assembly for a file
src/TextBox.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/TextBox.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/TextBox.cpp.s
.PHONY : src/TextBox.cpp.s

src/Texture.o: src/Texture.cpp.o

.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Texture.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i

.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Texture.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s

.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/Texture.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/WindowManager.o: src/WindowManager.cpp.o

.PHONY : src/WindowManager.o

# target to build an object file
src/WindowManager.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/WindowManager.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/WindowManager.cpp.o
.PHONY : src/WindowManager.cpp.o

src/WindowManager.i: src/WindowManager.cpp.i

.PHONY : src/WindowManager.i

# target to preprocess a source file
src/WindowManager.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/WindowManager.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/WindowManager.cpp.i
.PHONY : src/WindowManager.cpp.i

src/WindowManager.s: src/WindowManager.cpp.s

.PHONY : src/WindowManager.s

# target to generate assembly for a file
src/WindowManager.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/WindowManager.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/WindowManager.cpp.s
.PHONY : src/WindowManager.cpp.s

src/behaviors.o: src/behaviors.cpp.o

.PHONY : src/behaviors.o

# target to build an object file
src/behaviors.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/behaviors.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/behaviors.cpp.o
.PHONY : src/behaviors.cpp.o

src/behaviors.i: src/behaviors.cpp.i

.PHONY : src/behaviors.i

# target to preprocess a source file
src/behaviors.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/behaviors.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/behaviors.cpp.i
.PHONY : src/behaviors.cpp.i

src/behaviors.s: src/behaviors.cpp.s

.PHONY : src/behaviors.s

# target to generate assembly for a file
src/behaviors.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/behaviors.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/behaviors.cpp.s
.PHONY : src/behaviors.cpp.s

src/enemy.o: src/enemy.cpp.o

.PHONY : src/enemy.o

# target to build an object file
src/enemy.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/enemy.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/enemy.cpp.o
.PHONY : src/enemy.cpp.o

src/enemy.i: src/enemy.cpp.i

.PHONY : src/enemy.i

# target to preprocess a source file
src/enemy.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/enemy.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/enemy.cpp.i
.PHONY : src/enemy.cpp.i

src/enemy.s: src/enemy.cpp.s

.PHONY : src/enemy.s

# target to generate assembly for a file
src/enemy.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/enemy.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/enemy.cpp.s
.PHONY : src/enemy.cpp.s

src/enemy_manager.o: src/enemy_manager.cpp.o

.PHONY : src/enemy_manager.o

# target to build an object file
src/enemy_manager.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/enemy_manager.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/enemy_manager.cpp.o
.PHONY : src/enemy_manager.cpp.o

src/enemy_manager.i: src/enemy_manager.cpp.i

.PHONY : src/enemy_manager.i

# target to preprocess a source file
src/enemy_manager.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/enemy_manager.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/enemy_manager.cpp.i
.PHONY : src/enemy_manager.cpp.i

src/enemy_manager.s: src/enemy_manager.cpp.s

.PHONY : src/enemy_manager.s

# target to generate assembly for a file
src/enemy_manager.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/enemy_manager.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/enemy_manager.cpp.s
.PHONY : src/enemy_manager.cpp.s

src/entity.o: src/entity.cpp.o

.PHONY : src/entity.o

# target to build an object file
src/entity.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/entity.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/entity.cpp.o
.PHONY : src/entity.cpp.o

src/entity.i: src/entity.cpp.i

.PHONY : src/entity.i

# target to preprocess a source file
src/entity.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/entity.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/entity.cpp.i
.PHONY : src/entity.cpp.i

src/entity.s: src/entity.cpp.s

.PHONY : src/entity.s

# target to generate assembly for a file
src/entity.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/entity.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/entity.cpp.s
.PHONY : src/entity.cpp.s

src/player.o: src/player.cpp.o

.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/player.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i

.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/player.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s

.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/player.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/projectile.o: src/projectile.cpp.o

.PHONY : src/projectile.o

# target to build an object file
src/projectile.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/projectile.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/projectile.cpp.o
.PHONY : src/projectile.cpp.o

src/projectile.i: src/projectile.cpp.i

.PHONY : src/projectile.i

# target to preprocess a source file
src/projectile.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/projectile.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/projectile.cpp.i
.PHONY : src/projectile.cpp.i

src/projectile.s: src/projectile.cpp.s

.PHONY : src/projectile.s

# target to generate assembly for a file
src/projectile.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/projectile.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/projectile.cpp.s
.PHONY : src/projectile.cpp.s

src/sword.o: src/sword.cpp.o

.PHONY : src/sword.o

# target to build an object file
src/sword.cpp.o:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/sword.cpp.o
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/sword.cpp.o
.PHONY : src/sword.cpp.o

src/sword.i: src/sword.cpp.i

.PHONY : src/sword.i

# target to preprocess a source file
src/sword.cpp.i:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/sword.cpp.i
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/sword.cpp.i
.PHONY : src/sword.cpp.i

src/sword.s: src/sword.cpp.s

.PHONY : src/sword.s

# target to generate assembly for a file
src/sword.cpp.s:
	$(MAKE) -f CMakeFiles/swordthrow.dir/build.make CMakeFiles/swordthrow.dir/src/sword.cpp.s
	$(MAKE) -f CMakeFiles/sword_test.dir/build.make CMakeFiles/sword_test.dir/src/sword.cpp.s
.PHONY : src/sword.cpp.s

test/TestBase.o: test/TestBase.cpp.o

.PHONY : test/TestBase.o

# target to build an object file
test/TestBase.cpp.o:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestBase.cpp.o
.PHONY : test/TestBase.cpp.o

test/TestBase.i: test/TestBase.cpp.i

.PHONY : test/TestBase.i

# target to preprocess a source file
test/TestBase.cpp.i:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestBase.cpp.i
.PHONY : test/TestBase.cpp.i

test/TestBase.s: test/TestBase.cpp.s

.PHONY : test/TestBase.s

# target to generate assembly for a file
test/TestBase.cpp.s:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestBase.cpp.s
.PHONY : test/TestBase.cpp.s

test/TestEnemy.o: test/TestEnemy.cpp.o

.PHONY : test/TestEnemy.o

# target to build an object file
test/TestEnemy.cpp.o:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestEnemy.cpp.o
.PHONY : test/TestEnemy.cpp.o

test/TestEnemy.i: test/TestEnemy.cpp.i

.PHONY : test/TestEnemy.i

# target to preprocess a source file
test/TestEnemy.cpp.i:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestEnemy.cpp.i
.PHONY : test/TestEnemy.cpp.i

test/TestEnemy.s: test/TestEnemy.cpp.s

.PHONY : test/TestEnemy.s

# target to generate assembly for a file
test/TestEnemy.cpp.s:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestEnemy.cpp.s
.PHONY : test/TestEnemy.cpp.s

test/TestEntity.o: test/TestEntity.cpp.o

.PHONY : test/TestEntity.o

# target to build an object file
test/TestEntity.cpp.o:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestEntity.cpp.o
.PHONY : test/TestEntity.cpp.o

test/TestEntity.i: test/TestEntity.cpp.i

.PHONY : test/TestEntity.i

# target to preprocess a source file
test/TestEntity.cpp.i:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestEntity.cpp.i
.PHONY : test/TestEntity.cpp.i

test/TestEntity.s: test/TestEntity.cpp.s

.PHONY : test/TestEntity.s

# target to generate assembly for a file
test/TestEntity.cpp.s:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestEntity.cpp.s
.PHONY : test/TestEntity.cpp.s

test/TestGameMath.o: test/TestGameMath.cpp.o

.PHONY : test/TestGameMath.o

# target to build an object file
test/TestGameMath.cpp.o:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestGameMath.cpp.o
.PHONY : test/TestGameMath.cpp.o

test/TestGameMath.i: test/TestGameMath.cpp.i

.PHONY : test/TestGameMath.i

# target to preprocess a source file
test/TestGameMath.cpp.i:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestGameMath.cpp.i
.PHONY : test/TestGameMath.cpp.i

test/TestGameMath.s: test/TestGameMath.cpp.s

.PHONY : test/TestGameMath.s

# target to generate assembly for a file
test/TestGameMath.cpp.s:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestGameMath.cpp.s
.PHONY : test/TestGameMath.cpp.s

test/TestProjectile.o: test/TestProjectile.cpp.o

.PHONY : test/TestProjectile.o

# target to build an object file
test/TestProjectile.cpp.o:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestProjectile.cpp.o
.PHONY : test/TestProjectile.cpp.o

test/TestProjectile.i: test/TestProjectile.cpp.i

.PHONY : test/TestProjectile.i

# target to preprocess a source file
test/TestProjectile.cpp.i:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestProjectile.cpp.i
.PHONY : test/TestProjectile.cpp.i

test/TestProjectile.s: test/TestProjectile.cpp.s

.PHONY : test/TestProjectile.s

# target to generate assembly for a file
test/TestProjectile.cpp.s:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestProjectile.cpp.s
.PHONY : test/TestProjectile.cpp.s

test/TestSword.o: test/TestSword.cpp.o

.PHONY : test/TestSword.o

# target to build an object file
test/TestSword.cpp.o:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestSword.cpp.o
.PHONY : test/TestSword.cpp.o

test/TestSword.i: test/TestSword.cpp.i

.PHONY : test/TestSword.i

# target to preprocess a source file
test/TestSword.cpp.i:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestSword.cpp.i
.PHONY : test/TestSword.cpp.i

test/TestSword.s: test/TestSword.cpp.s

.PHONY : test/TestSword.s

# target to generate assembly for a file
test/TestSword.cpp.s:
	$(MAKE) -f CMakeFiles/project_test.dir/build.make CMakeFiles/project_test.dir/test/TestSword.cpp.s
.PHONY : test/TestSword.cpp.s

thirdparty/glad.o: thirdparty/glad.c.o

.PHONY : thirdparty/glad.o

# target to build an object file
thirdparty/glad.c.o:
	$(MAKE) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/thirdparty/glad.c.o
.PHONY : thirdparty/glad.c.o

thirdparty/glad.i: thirdparty/glad.c.i

.PHONY : thirdparty/glad.i

# target to preprocess a source file
thirdparty/glad.c.i:
	$(MAKE) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/thirdparty/glad.c.i
.PHONY : thirdparty/glad.c.i

thirdparty/glad.s: thirdparty/glad.c.s

.PHONY : thirdparty/glad.s

# target to generate assembly for a file
thirdparty/glad.c.s:
	$(MAKE) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/thirdparty/glad.c.s
.PHONY : thirdparty/glad.c.s

thirdparty/stb_image.o: thirdparty/stb_image.cpp.o

.PHONY : thirdparty/stb_image.o

# target to build an object file
thirdparty/stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/STB_IMAGE.dir/build.make CMakeFiles/STB_IMAGE.dir/thirdparty/stb_image.cpp.o
.PHONY : thirdparty/stb_image.cpp.o

thirdparty/stb_image.i: thirdparty/stb_image.cpp.i

.PHONY : thirdparty/stb_image.i

# target to preprocess a source file
thirdparty/stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/STB_IMAGE.dir/build.make CMakeFiles/STB_IMAGE.dir/thirdparty/stb_image.cpp.i
.PHONY : thirdparty/stb_image.cpp.i

thirdparty/stb_image.s: thirdparty/stb_image.cpp.s

.PHONY : thirdparty/stb_image.s

# target to generate assembly for a file
thirdparty/stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/STB_IMAGE.dir/build.make CMakeFiles/STB_IMAGE.dir/thirdparty/stb_image.cpp.s
.PHONY : thirdparty/stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ExperimentalStart"
	@echo "... GLAD"
	@echo "... Nightly"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousStart"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyUpdate"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... STB_IMAGE"
	@echo "... Continuous"
	@echo "... swordthrow"
	@echo "... ContinuousBuild"
	@echo "... Experimental"
	@echo "... edit_cache"
	@echo "... ExperimentalUpdate"
	@echo "... rebuild_cache"
	@echo "... NightlyTest"
	@echo "... ExperimentalBuild"
	@echo "... ContinuousUpdate"
	@echo "... NightlySubmit"
	@echo "... NightlyBuild"
	@echo "... ContinuousTest"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalMemCheck"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... sword_test"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousMemCheck"
	@echo "... ExperimentalConfigure"
	@echo "... ContinuousSubmit"
	@echo "... project_test"
	@echo "... test"
	@echo "... src/Collision.o"
	@echo "... src/Collision.i"
	@echo "... src/Collision.s"
	@echo "... src/Control.o"
	@echo "... src/Control.i"
	@echo "... src/Control.s"
	@echo "... src/Controller.o"
	@echo "... src/Controller.i"
	@echo "... src/Controller.s"
	@echo "... src/DungeonMap.o"
	@echo "... src/DungeonMap.i"
	@echo "... src/DungeonMap.s"
	@echo "... src/DungeonTile.o"
	@echo "... src/DungeonTile.i"
	@echo "... src/DungeonTile.s"
	@echo "... src/FileLoader.o"
	@echo "... src/FileLoader.i"
	@echo "... src/FileLoader.s"
	@echo "... src/GameMath.o"
	@echo "... src/GameMath.i"
	@echo "... src/GameMath.s"
	@echo "... src/GameRunner.o"
	@echo "... src/GameRunner.i"
	@echo "... src/GameRunner.s"
	@echo "... src/Graphics.o"
	@echo "... src/Graphics.i"
	@echo "... src/Graphics.s"
	@echo "... src/Hud.o"
	@echo "... src/Hud.i"
	@echo "... src/Hud.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/MainMenu.o"
	@echo "... src/MainMenu.i"
	@echo "... src/MainMenu.s"
	@echo "... src/ResourceManager.o"
	@echo "... src/ResourceManager.i"
	@echo "... src/ResourceManager.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/System.o"
	@echo "... src/System.i"
	@echo "... src/System.s"
	@echo "... src/TextBox.o"
	@echo "... src/TextBox.i"
	@echo "... src/TextBox.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/WindowManager.o"
	@echo "... src/WindowManager.i"
	@echo "... src/WindowManager.s"
	@echo "... src/behaviors.o"
	@echo "... src/behaviors.i"
	@echo "... src/behaviors.s"
	@echo "... src/enemy.o"
	@echo "... src/enemy.i"
	@echo "... src/enemy.s"
	@echo "... src/enemy_manager.o"
	@echo "... src/enemy_manager.i"
	@echo "... src/enemy_manager.s"
	@echo "... src/entity.o"
	@echo "... src/entity.i"
	@echo "... src/entity.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/projectile.o"
	@echo "... src/projectile.i"
	@echo "... src/projectile.s"
	@echo "... src/sword.o"
	@echo "... src/sword.i"
	@echo "... src/sword.s"
	@echo "... test/TestBase.o"
	@echo "... test/TestBase.i"
	@echo "... test/TestBase.s"
	@echo "... test/TestEnemy.o"
	@echo "... test/TestEnemy.i"
	@echo "... test/TestEnemy.s"
	@echo "... test/TestEntity.o"
	@echo "... test/TestEntity.i"
	@echo "... test/TestEntity.s"
	@echo "... test/TestGameMath.o"
	@echo "... test/TestGameMath.i"
	@echo "... test/TestGameMath.s"
	@echo "... test/TestProjectile.o"
	@echo "... test/TestProjectile.i"
	@echo "... test/TestProjectile.s"
	@echo "... test/TestSword.o"
	@echo "... test/TestSword.i"
	@echo "... test/TestSword.s"
	@echo "... thirdparty/glad.o"
	@echo "... thirdparty/glad.i"
	@echo "... thirdparty/glad.s"
	@echo "... thirdparty/stb_image.o"
	@echo "... thirdparty/stb_image.i"
	@echo "... thirdparty/stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

